name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Git
        run: |
          git config --global user.name "Conventional Changelog Action"
          git config --global user.email "conventional.changelog.action@github.com"
          git checkout ${{ github.head_ref }}

      - name: Conventional Commits
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './package/package.json'
          skip-version-file: false
          skip-commit: false
          skip-tag: false
          release-count: 0
          output-file: 'CHANGELOG.md'
