name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional Commits
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "./package/package.json"
          skip-version-file: false
          skip-commit: false
          skip-tag: false
          release-count: 0
          output-file: "CHANGELOG.md"
